dataset:
  train_dir: ./dataset/train_data
  test_dir: ./dataset/test_data
  height: 224
  width: 224

training:
  batch_size: 8
  epochs: 50
  learning_rate: 1e-3

model:
  name: inception_resnet #vgg, resnet, inception_resnet, mobilenet
  save_path: ./training
